name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: |
          cd $GITHUB_WORKSPACE
          chmod +x ./gradlew
          ls -la

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-29" "system-images;android-29;default;arm64-v8a" "emulator"
          sdkmanager --install "system-images;android-29;default;arm64-v8a"
          echo "no" | avdmanager create avd -n test_device -k "system-images;android-29;default;arm64-v8a" --force

      - name: Run Unit Tests
        run: |
          cd $GITHUB_WORKSPACE
          ./gradlew test --stacktrace

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: arm64-v8a
          profile: Pixel_2
          cores: 2
          ram-size: 4096M
          emulator-boot-timeout: 900
          script: |
            cd $GITHUB_WORKSPACE
            ./gradlew connectedDebugAndroidTest --stacktrace

      - name: Create Test Reports Directory
        if: always()
        run: |
          mkdir -p app/build/reports/tests
          mkdir -p app/build/reports/androidTests/connected
          mkdir -p app/build/outputs/androidTest-results

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            app/build/reports/tests/
            app/build/reports/androidTests/connected/
            app/build/outputs/androidTest-results/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace