name: Android Instrumentation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-instrumentation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Match the version used in your project

      - name: Configure Android environment
        uses: actions/setup-android@v2
        with:
          # Choose the correct API level for your project
          api-level: 34
          # Use the default Android SDK
          sdk-root: "$HOME/android-sdk"
          # Install necessary packages
          # (Adjust this to your project's needs)
          packages: build-tools;platform-tools;cmake;ndk-bundle;platform-34

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run instrumentation tests
        uses: actions/github-script@v6
        with:
          script: |
            const { exec } = require('child_process');
            exec('./gradlew connectedAndroidTest', { cwd: '.' }, (error, stdout, stderr) => {
              if (error) {
                console.error(`Error: ${error}`);
                core.setFailed('Instrumentation tests failed');
              } else {
                console.log('Instrumentation tests successful!');
              }
            });