name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11]
        android-target: [30, 31]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}

      - name: Set up Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-target }}
          target: android-${{ matrix.android-target }}
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-window

      - name: Build the project
        run: ./gradlew build

      - name: Run instrumentation tests
        run: ./gradlew connectedDebugAndroidTest

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/TEST-*xml
